#
# Build our container that runs Splunk Lab with the Telegram app addin
#

FROM dmuth1/splunk-lab

COPY nlp-text-analytics_114.tgz nlp-text-analytics_114.tgz
RUN tar xfvz nlp-text-analytics_114.tgz \
        && mv nlp-text-analytics /opt/splunk/etc/apps/ \
        && rm -fv /tmp/nlp-text-analytics_114.tgz

#
# Copy in our application
#
COPY splunk-app/ /opt/splunk/etc/apps/splunk-telegram


